// src/utils/languageList.js

// supported languages can be found at textrazor.com/languages | 19 languages as of now
// these languages are natively supported by textRazor for tag generation
export const supportedLanguages = [
  "ar",
  "en",
  "zh",
  "da",
  "nl",
  "fi",
  "fr",
  "de",
  "el",
  "it",
  "ja",
  "ko",
  "no",
  "pl",
  "pt",
  "ru",
  "es",
  "sv",
  "uk",
];

// translation dependant languages are: (60 - 19 = 41)
// (languages provided by github.com/nitotm/efficient-language-detector-js library) minus (supported Languages by text razor)
// we detect the languages of all the texts and if they were in this list, we send them to google translate api (if not, we don't process those requests at all)
// from there, all of these list's languages will be translated to english and we can use it in textRazor API to generate english tags
export const translationDependantLanguages = [
  "am",
  "az",
  "be",
  "bg",
  "bn",
  "ca",
  "cs",
  "et",
  "eu",
  "fa",
  "gu",
  "he",
  "hi",
  "hr",
  "hu",
  "hy",
  "is",
  "ka",
  "kn",
  "ku",
  "lo",
  "lt",
  "lv",
  "ml",
  "mr",
  "ms",
  "or",
  "pa",
  "ro",
  "sk",
  "sl",
  "sq",
  "sr",
  "ta",
  "te",
  "th",
  "tl",
  "tr",
  "ur",
  "vi",
  "yo",
];

// All languages with their names and flags (includeing native languages and translation-dependant languages)
export const languages = {
  // native languages
  ar: { name: "Arabic", flag: "🇸🇦" },
  en: { name: "English", flag: "🇬🇧" },
  zh: { name: "Chinese", flag: "🇨🇳" },
  da: { name: "Danish", flag: "🇩🇰" },
  nl: { name: "Dutch", flag: "🇳🇱" },
  fi: { name: "Finnish", flag: "🇫🇮" },
  fr: { name: "French", flag: "🇫🇷" },
  de: { name: "German", flag: "🇩🇪" },
  el: { name: "Greek", flag: "🇬🇷" },
  it: { name: "Italian", flag: "🇮🇹" },
  ja: { name: "Japanese", flag: "🇯🇵" },
  ko: { name: "Korean", flag: "🇰🇷" },
  no: { name: "Norwegian", flag: "🇳🇴" },
  pl: { name: "Polish", flag: "🇵🇱" },
  pt: { name: "Portuguese", flag: "🇵🇹" },
  ru: { name: "Russian", flag: "🇷🇺" },
  es: { name: "Spanish", flag: "🇪🇸" },
  sv: { name: "Swedish", flag: "🇸🇪" },
  uk: { name: "Ukrainian", flag: "🇺🇦" },
  // Translation Dependant Languages
  am: { name: "Amharic", flag: "🇪🇹" },
  az: { name: "Azerbaijani", flag: "🇦🇿" },
  be: { name: "Belarusian", flag: "🇧🇾" },
  bg: { name: "Bulgarian", flag: "🇧🇬" },
  bn: { name: "Bengali", flag: "🇧🇩" },
  ca: { name: "Catalan", flag: "🇪🇸" },
  cs: { name: "Czech", flag: "🇨🇿" },
  et: { name: "Estonian", flag: "🇪🇪" },
  eu: { name: "Basque", flag: "🇪🇸" },
  fa: { name: "Persian", flag: "🇮🇷" },
  gu: { name: "Gujarati", flag: "🇮🇳" },
  he: { name: "Hebrew", flag: "🇮🇱" },
  hi: { name: "Hindi", flag: "🇮🇳" },
  hr: { name: "Croatian", flag: "🇭🇷" },
  hu: { name: "Hungarian", flag: "🇭🇺" },
  hy: { name: "Armenian", flag: "🇦🇲" },
  is: { name: "Icelandic", flag: "🇮🇸" },
  ka: { name: "Georgian", flag: "🇬🇪" },
  kn: { name: "Kannada", flag: "🇮🇳" },
  ku: { name: "Kurdish", flag: "🇮🇶" },
  lo: { name: "Lao", flag: "🇱🇦" },
  lt: { name: "Lithuanian", flag: "🇱🇹" },
  lv: { name: "Latvian", flag: "🇱🇻" },
  ml: { name: "Malayalam", flag: "🇮🇳" },
  mr: { name: "Marathi", flag: "🇮🇳" },
  ms: { name: "Malay", flag: "🇲🇾" },
  or: { name: "Oriya", flag: "🇮🇳" },
  pa: { name: "Punjabi", flag: "🇮🇳" },
  ro: { name: "Romanian", flag: "🇷🇴" },
  sk: { name: "Slovak", flag: "🇸🇰" },
  sl: { name: "Slovene", flag: "🇸🇮" },
  sq: { name: "Albanian", flag: "🇦🇱" },
  sr: { name: "Serbian", flag: "🇷🇸" },
  ta: { name: "Tamil", flag: "🇮🇳" },
  te: { name: "Telugu", flag: "🇮🇳" },
  th: { name: "Thai", flag: "🇹🇭" },
  tl: { name: "Tagalog", flag: "🇵🇭" },
  tr: { name: "Turkish", flag: "🇹🇷" },
  ur: { name: "Urdu", flag: "🇵🇰" },
  vi: { name: "Vietnamese", flag: "🇻🇳" },
  yo: { name: "Yoruba", flag: "🇳🇬" },
};
